security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            oauth:
                login_path: /connect/bitbucket
                use_forward: false
                failure_path: /login
                resource_owners:
                    bitbucket:          "/login/check-bitbucket"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    access_control:
        - { path: ^/login/?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/edit, allow-if: "not has_role('ROLE_OAUTH_USER')" }
        - { path: ^/profile/change-password, allow-if: "not has_role('ROLE_OAUTH_USER')" }
        - { path: ^/admin/jobs/, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_OAUTH_USER:  ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
